# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaTeresina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.CharField(max_length=8)),
                ('temperatura', models.FloatField(default=0)),
                ('sensacao', models.FloatField(default=0)),
                ('umidade', models.FloatField(default=0)),
                ('pressao', models.FloatField(default=0)),
                ('vento', models.FloatField(default=0)),
            ],
        ),
    ]
